name: Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        extras:
          - ''
          - '[speedups]'
          - '[speedups,rasterio]'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade Python bits
      run: |
        python -m pip install --upgrade pip coverage wheel setuptools
    - name: Install development files
      if: matrix.python-version == '3.9'
      run: |
        sudo apt-get install -y fftw3-dev
        python -m pip install Cython
    - name: Install app
      run: python -m pip install --ignore-requires-python -e ."$EXTRAS"
      env:
        EXTRAS: '${{ matrix.extras }}'
    - name: Run app with coverage
      run: coverage run -m image_similarity_measures.evaluate --metric all --org_img_path=example/lafayette_org.tif --pred_img_path=example/lafayette_pred.tif
    - name: Report coverage
      continue-on-error: true
      run: coverage report
